[project]
name = "spoo-me"
version = "1.0.0"
description = "Open-Source URL Shortener Written in Flask"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "crawlerdetect>=0.3.0",
    "dicttoxml>=1.7.16",
    "emoji>=2.14.1",
    "flask>=3.1.1",
    "flask-caching>=2.3.1",
    "flask-cors>=6.0.0",
    "flask-limiter[mongodb]>=3.11.0",
    "geoip2>=5.1.0",
    "gunicorn>=23.0.0",
    "openpyxl>=3.1.5",
    "pycountry>=24.6.1",
    "pymongo>=4.13.0",
    "python-dotenv>=1.1.0",
    "redis>=6.2.0",
    "requests>=2.32.3",
    "tldextract>=5.3.0",
    "user-agents>=2.2.0",
    "validators>=0.35.0",
]

[dependency-groups]
dev = [
    "mongomock>=4.3.0",
    "pytest>=8.3.5",
    "pytest-flask>=1.3.0",
    "pytest-mock>=3.14.1",
    "requests-mock>=1.12.1",
    "ruff>=0.11.11",
    "uv>=0.7.8",
]
