[tool.poetry]
name = "spoo-me"
version = "1.0.0"
description = "Open-Source URL Shortener Written in Flask"
authors = ["Zingzy <admin@spoo.me>"]
license = "APACHE-2.0"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"
Flask = "^3.0.3"
flask-cors = "^5.0.0"
geoip2 = "^4.8.0"
pymongo = "^4.11.1"
python-dotenv = "^1.0.1"
requests = "^2.32.3"
user-agents = "^2.2.0"
tldextract = "^5.1.2"
emoji = "^2.14.0"
openpyxl = "^3.1.5"
dicttoxml = "^1.7.16"
validators = "^0.34.0"
gunicorn = "^23.0.0"
crawlerdetect = "^0.1.7"
pycountry = "^24.6.1"
flask-caching = "^2.3.0"
pytest = "^8.3.3"
requests-mock = "^1.12.1"
pytest-mock = "^3.14.0"
pytest-flask = "^1.3.0"
mongomock = "^4.2.0.post1"
flask-limiter = {extras = ["mongodb"], version = "^3.9.2"}
ruff = "^0.9.6"
redis = "^5.2.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
